### ISSUE TITLE
FYI/Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [TheRandomLabs/RandomTweaks#10]
Just installed RT, instant crash

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  RBLoadingPlugin (RealBench-1.12-1.3.3.jar)
  IMLoadingPlugin (infinimend-1.12-1.0.1.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.3.jar)
  MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 8/19/17 5:41 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from RandomTweaks (randomtweaks)
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:592)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:227)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: net.minecraft.util.ReportedException: A problem with the RandomTweaks configuration occurred.
	at com.therandomlabs.randomtweaks.common.RTConfig.resetConfigIfNecessary(RTConfig.java:493)
	at com.therandomlabs.randomtweaks.common.RTConfig.<clinit>(RTConfig.java:255)
	... 39 more
Caused by: java.nio.file.NoSuchFileException: config\randomtweaks\dontresetconfig.txt
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.write(Files.java:3351)
	at java.nio.file.Files.write(Files.java:3397)
	at com.therandomlabs.randomtweaks.common.RTConfig.resetConfigIfNecessary(RTConfig.java:489)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 307806744 bytes (293 MB) / 781312000 bytes (745 MB) up to 12831227904 bytes (12236 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx12G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2443 93 mods loaded, 93 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2443.jar) 
	UC	forge{14.21.1.2443} [Minecraft Forge] (forge-1.12-14.21.1.2443.jar) 
	UC	infinimend{1.0.1} [Infinity & Mending Unnerf] (minecraft.jar) 
	UC	ivtoolkit{1.3.3-1.12} [IvToolkit] (minecraft.jar) 
	UC	backpacks16840{3.2.1} [Backpacks!] (zz-backpacks 1.12 - 3.2.1.jar) 
	UC	simplebedrolls{1.0} [Simple Bedrolls] ([1.12]SimpleBedrolls-1.0.jar) 
	UC	uncraftingtable{1.8-beta4} [Uncrafting Table] ([1.12]UncraftingTable-1.8-beta4.jar) 
	UC	jei{4.7.5.88} [Just Enough Items] (jei_1.12.1-4.7.5.88.jar) 
	UC	abyssalcraft{1.9.4-pre-4} [AbyssalCraft] (AbyssalCraft-1.12-1.9.4-pre-4.jar) 
	UC	actuallyadditions{1.12-r117} [Actually Additions] (ActuallyAdditions-1.12-r117.jar) 
	UC	baubles{1.5.1} [Baubles] (Baubles-1.12-1.5.1.jar) 
	UC	actuallybaubles{1.1} [Actually Baubles] (ActuallyBaubles-1.12-1.1.jar) 
	UC	ambientsounds{2.0.0} [AmbientSounds] (AmbientSounds v2.0.7 mc1.12.jar) 
	UC	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UC	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UC	bibliocraft{2.4.3} [BiblioCraft] (BiblioCraft[v2.4.3][MC1.12.0].jar) 
	UC	biomesoplenty{7.0.0.2291} [Biomes O' Plenty] (BiomesOPlenty-1.12-7.0.0.2291-universal.jar) 
	UC	birdsnests{2.0.0} [Bird's Nests] (BirdsNests1.12-2.0.0.jar) 
	UC	bookshelf{2.0.415} [Bookshelf] (Bookshelf-1.12-2.0.0.415.jar) 
	UC	carryon{1.1.1} [Carry On] (CarryOn MC1.12 v1.1.1.jar) 
	UC	chisel{MC1.12-0.0.13.15} [Chisel] (Chisel-MC1.12-0.0.13.15.jar) 
	UC	clarity{1.0} [Clarity] (clarity-1.0.jar) 
	UC	cleanview{1.10.2-v1} [CleanView] (CleanView-1.10.2-v1.jar) 
	UC	clockhud{1.4.0} [Clock HUD] (ClockHUD-1.12-1.4.0.jar) 
	UC	pillar_extension_biomesoplenty{3.0.0} [Corail Pillar - Biomes O'Plenty Extension] (corail_pillar_extension_biomesoplenty-3.0.0-1.12.0.jar) 
	UC	pillar_extension_chisel{1.1.0} [Corail Pillar - Chisel Extension] (corail_pillar_extension_chisel-1.1.0-1.12.0.jar) 
	UC	mantle{1.12-1.3.1.18} [Mantle] (Mantle-1.12-1.3.1.18.jar) 
	UC	natura{1.12-4.3.0.16} [Natura] (Natura-1.12-4.3.0.16.jar) 
	UC	forestry{5.5.0.170} [Forestry] (forestry_1.12.1-5.5.0.170.jar) 
	UC	pillar_extension_forestry{2.0.0} [Corail Pillar - Forestry Extension] (corail_pillar_extension_forestry-2.0.0-1.12.0.jar) 
	UC	pillar_extension_quark{3.1.0} [Corail Pillar - Quark Extension] (corail_pillar_extension_quark-3.1.0-1.12.0.jar) 
	UC	cs{3.0.0} [Configurable Villager to Door Ratio] (cs-3.0.0.jar) 
	UC	ctm{MC1.12-0.2.1.5} [CTM] (CTM-MC1.12-0.2.1.5.jar) 
	UC	customizeddungeonloot{1.0.1} [§eCustomized Dungeon Loot] (Customized Dungeon Loot (v.1.0.1).jar) 
	UC	cyclicmagic{1.7.9} [Cyclic] (Cyclic-1.12-1.7.9.jar) 
	UC	cyclopscore{0.10.12} [Cyclops Core] (CyclopsCore-1.12-0.10.12.jar) 
	UC	waila{1.8.20} [Waila] (Hwyla-1.8.20-B35_1.12.jar) 
	UC	darkutils{1.6.167} [Dark Utilities] (DarkUtils-1.12-1.6.167.jar) 
	UC	dsurround{3.4.6.3} [Dynamic Surroundings] (DynamicSurroundings-1.12-3.4.6.3.jar) 
	UC	presets{3.4.6.3} [Presets!] (DynamicSurroundings-1.12-3.4.6.3.jar) 
	UC	earthworks{1.3.4.3} [Earthworks] (Earthworks-1.12-1.3.4.3.jar) 
	UC	elevatorid{1.3.4} [Elevator Mod] (ElevatorMod-1.12-1.3.4.jar) 
	UC	csb_ench_table{1.1.2} [Lapis Stays in the Enchanting Table] (EnchantingTable-1.12-1.1.2.jar) 
	UC	enchdesc{1.0.4} [Enchantment Descriptions] (EnchantmentDescriptions-1.12-1.0.4.jar) 
	UC	everlastingabilities{1.3.2} [EverlastingAbilities] (EverlastingAbilities-1.12-1.3.2.jar) 
	UC	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.12-1.5.2.jar) 
	UC	friendlyfire{1.5.5} [Friendly Fire] (FriendlyFire-1.12-1.5.5.jar) 
	UC	silentlib{2.2.7} [Silent Lib] (SilentLib-1.12-2.2.7-85.jar) 
	UC	funores{1.5.7} [Fun Ores] (FunOres-1.12-1.5.7-117.jar) 
	UC	gravestone{1.0.12} [Gravestone] (GraveStone-1.12-Graves-1.0.12.jar) 
	UC	guideapi{1.12-2.1.4-56} [Guide-API] (Guide-API-1.12-2.1.4-56.jar) 
	UC	iv{3.0.0} [Improved Villagers] (Improved Villagers-3.0.0.jar) 
	UC	improvedbackpacks{1.12-1.1.2.0} [Improved Backpacks] (ImprovedBackpacks-1.12-1.1.2.0.jar) 
	UC	inventorytweaks{1.62+release.90.40cf8fc} [Inventory Tweaks] (InventoryTweaks-1.62.jar) 
	UC	itemscroller{0.11.0} [Item Scroller] (itemscroller-1.12.0-0.11.0.jar) 
	UC	jeibees{0.9.0.2} [JEI Bees] (jeibees-0.9.0.2-mc1.12.jar) 
	UC	jeiintegration{1.4.1.30} [JEI Integration] (jeiintegration_1.12.1-1.4.1.30.jar) 
	UC	journeymap{1.12-5.4.9} [JourneyMap] (journeymap-1.12-5.4.9.jar) 
	UC	levelup2{${version}} [Level Up! Reloaded] (Level Up! 2-1.1.4-1.12.jar) 
	UC	malisiscore{1.12-6.0.4} [MalisisCore] (malisiscore-1.12-6.0.4.jar) 
	UC	malisisblocks{1.12-6.0.2} [Malisis Blocks] (malisisblocks-1.12-6.0.2.jar) 
	UC	malisisdoors{1.12-7.0.4} [MalisisDoors] (malisisdoors-1.12-7.0.4.jar) 
	UC	malisisswitches{1.12-5.0.0} [Malisis Switches] (malisisswitches-1.12-5.0.0.jar) 
	UC	mobfarm{2.2.1} [Mob Farm] (Mob Farm-1.12-2.2.1.jar) 
	UC	mob_grinding_utils{0.3.2} [mob_grinding_utils] (MobGrindingUtils-0.3.2.jar) 
	UC	modernlamps{1.0.3} [Modern Lights] (ModernLights-1.0.3_1.12.jar) 
	UC	moreloottables{0.1.0} [More Loot Tables] (moreloottables-1.12.0-0.1.0.jar) 
	UC	notenoughwands{1.5.9} [Not Enough Wands] (notenoughwands-1.12-1.5.9.jar) 
	UC	oreshrubs{1.4.0} [Ore Shrubs] (oreshrubs-1.4.0-1.12.jar) 
	UC	quickleafdecay{1.2.3} [Quick Leaf Decay] (QuickLeafDecay-MC1.12-1.2.3.jar) 
	UC	randomthings{4.0.5} [Random Things] (RandomThings-MC1.12.1-4.0.5.jar) 
	UE	randomtweaks{1.12.1-2.1.0.0} [RandomTweaks] (randomtweaks-1.12.1-2.1.0.0.jar) 
	UC	reccomplex{1.4.5} [Recurrent Complex] (RecurrentComplex-1.4.5.jar) 
	UC	woodenshears{@MAJOR@.@MINOR@.@REVIS@.@BUILD@} [Wooden Shears] (SBM-WoodenShears-1.12-0.0.1b7.jar) 
	UC	scannable{1.4.1.7} [Scannable] (Scannable-MC1.12-1.4.1.7.jar) 
	UC	icc{0.2.2} [Simple Item Collector Chest] (Simple Item Collector Chest-0.2.2.jar) 
	UC	simpleleather{1.12-1.0} [Simple Leather] (simpleleather-1.12-1.0.jar) 
	UC	simplemagnet{1.12.0-1.2.6} [Simple Magnet] (simplemagnet-1.12.0-1.2.6.jar) 
	UC	soundfilters{0.10_for_1.12} [Sound Filters] (SoundFilters-0.10_for_1.12.jar) 
	UC	spawnercraft{4.0.0} [SpawnerCraft] (SpawnerCraft 1.12-4.0.0.jar) 
	UC	muchmorechickens{1.7} [muchmorechickens] (TMC-1.12-1.7.jar) 
	UC	toolbelt{1.7.1} [Tool Belt] (ToolBelt-1.12.0-1.7.1.jar) 
	UC	treechopper{1.2.1} [Tree Chopper] (TreeChopper-1.12-1.2.1.jar) 
	UC	uncrafted{3.0.0pre2} [Uncrafted Mod] (Uncrafted 1.12 (v.3.0.0pre2).jar) 
	UC	veinminer{0.38.1} [Vein Miner] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UC	veinminermodsupport{0.38.1} [Mod Support] (VeinMiner-1.12-0.38.1.639+134fb1e.jar) 
	UC	villagermarket{1.0} [Villager Market] (villagermarket-0.2-HF.jar) 
	UC	vtt{0.6.4} [Villager Trade Tables] (VillagerTrades-1.12-0.6.4.jar) 
	UC	wawla{2.5.239} [What Are We Looking At] (Wawla-1.12-2.5.239.jar) 
	UC	waystones{4.0.15} [Waystones] (Waystones_1.12.1-4.0.15.jar) 
	UC	corail_pillar{3.1.3} [Corail Pillar] (corail_pillar-3.1.3-1.12.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.12 - 3.2.1.jar)
  brad16840.common.asm.ClassTransformer
RBLoadingPlugin (RealBench-1.12-1.3.3.jar)
  pw.prok.realbench.asm.RBTransformer
IMLoadingPlugin (infinimend-1.12-1.0.1.jar)
  net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.62.jar)
  invtweaks.forge.asm.ContainerTransformer
MalisisCorePlugin (malisiscore-1.12-6.0.4.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.1.5.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (RandomThings-MC1.12.1-4.0.5.jar)
  lumien.randomthings.asm.ClassTransformer
DynamicSurroundingsCore (DynamicSurroundings-1.12-3.4.6.3.jar)
  org.blockartistry.DynSurround.asm.Transformer
MalisisSwitchesPlugin (malisisswitches-1.12-5.0.0.jar)
  net.malisis.switches.asm.MalisisSwitchesTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 384.94' Renderer: 'GeForce GTX 1050 Ti/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

**Comment by TheRandomLabs** [comment]
Sorry about that, I'll fix it immediately.
