### ISSUE TITLE
Server console spam with armor stand

### ISSUE THREAD

**Issue by LemADEC** [TheRandomLabs/RandomTweaks#53]
As of randomtweaks-1.12.2-2.7.0.1, a console spam is observed when trying to sneak-right click an armor stand, from using client side class on a dedicated server.

```
[17:15:43] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent$EntityInteractSpecific@22928c7f:
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
>       at com.therandomlabs.randomtweaks.client.ArmorEquipSoundHandler.<clinit>(ArmorEquipSoundHandler.java:16) ~[ArmorEquipSoundHandler.class:?]
>       at com.therandomlabs.randomtweaks.common.MiscEventHandler.onEntityInteractSpecific(MiscEventHandler.java:494) ~[MiscEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_252_MiscEventHandler_onEntityInteractSpecific_EntityInteractSpecific.invoke(.dynamic) ~[?:?]
>       at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1252) [EventBus.class:?]
>       at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:1207) [EventBus.class:?]
>       at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostEntityInteractEvent(SpongeToForgeEventFactory.java:876) [SpongeToForgeEventFactory.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.mod.event.SpongeToForgeEventFactory.createAndPostForgeEvent(SpongeToForgeEventFactory.java:243) [SpongeToForgeEventFactory.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:337) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:446) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:415) [SpongeModEventManager.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:465) [SpongeEventManager.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:247) [SpongeImpl.class:1.12.2-2838-7.1.7-RC3884]
>       at org.spongepowered.common.event.SpongeCommonEventFactory.callInteractEntityEventSecondary(SpongeCommonEventFactory.java:774) [SpongeCommonEventFactory.class:1.12.2-2838-7.1.7-RC3884]
>       at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:3663) [pa.class:?]
>       at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:69) [li.class:?]
>       at net.minecraft.network.play.client.CPacketUseEntity.func_148833_a(SourceFile:13) [li.class:?]
>       at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:191) [PacketPhaseUtil.class:1.12.2-2838-7.1.7-RC3884]
>       at net.minecraft.network.PacketThreadUtil$1.redirect$impl$redirectToPhaseTracker$zlh000(SourceFile:540) [hv$1.class:?]
>       at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
>       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_212]
>       at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_212]
>       at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
>       at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2838-7.1.7-RC3884]
>       at net.minecraft.server.MinecraftServer.redirect$onRun$zjl000(MinecraftServer.java:4715) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.Minecraft
>       at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
>       at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
>       ... 30 more
```

**Comment by TheRandomLabs** [comment]
Whoops, I'll fix this as soon as I can.

>
