### ISSUE TITLE
Mod incorpertible with SleepingBegs

### ISSUE THREAD

**Issue by TheSirati97** [TheRandomLabs/RandomTweaks#8]
When sleeping in a Sleeping Bag of the mod SleepingBags the following exception is thrown:
`
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
        at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196) ~[art$a.class:?]
        at com.therandomlabs.randomtweaks.common.SleepHandler.onSleep(SleepHandler.java:43) ~[SleepHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_21_SleepHandler_onSleep_PlayerSleepInBedEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
        at net.shadowfacts.sleepingbag.ItemSleepingBag.vanillaCanSleep(ItemSleepingBag.java:160) ~[ItemSleepingBag.class:?]
        at net.shadowfacts.sleepingbag.ItemSleepingBag.canPlayerSleep(ItemSleepingBag.java:181) ~[ItemSleepingBag.class:?]
        at net.shadowfacts.sleepingbag.ItemSleepingBag.onArmorTick(ItemSleepingBag.java:128) ~[ItemSleepingBag.class:?]
        at net.minecraft.entity.player.InventoryPlayer.func_70429_k(InventoryPlayer.java:353) ~[zr.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:510) ~[zs.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2013) ~[sf.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233) ~[zs.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303) ~[lu.class:?]
        ... 9 more
`

**Comment by TheRandomLabs** [comment]
Thanks for reporting, I'll look into it.

**Comment by TheRandomLabs** [comment]
Fixed in 1.11.2-1.8.0.2.
